name: reusemart_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_carousel_slider: ^1.1.0
  flutter_riverpod: ^2.6.1
  http: ^1.3.0
  shared_preferences: ^2.2.2
  firebase_core: ^2.30.0
  firebase_messaging: ^14.7.10
  flutter_local_notifications: ^17.0.0
  cached_network_image: ^3.2.3
  flutter_localizations:
    sdk: flutter



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
  - images/

fonts:
  - family: "Poppins-Bold"
    fonts:
      - asset: fonts/Poppins-Bold.ttf

  - family: "Poppins-SemiBold"
    fonts:
      - asset: fonts/Poppins-SemiBold.ttf

  - family: "Poppins-Medium"
    fonts:
      - asset: fonts/Poppins-Medium.ttf

  - family: "Poppins-Regular"
    fonts:
      - asset: fonts/Poppins-Regular.ttf

  - family: "Poppins-Light"
    fonts:
      - asset: fonts/Poppins-Light.ttf
